# Generated by Django 5.2 on 2025-07-20 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_ciudadano_telefono_funcionario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
