# Generated by Django 5.2 on 2025-07-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_ciudadano_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
