# Generated by Django 5.2 on 2025-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='evidencias'),
        ),
    ]
