# Generated by Django 5.2 on 2025-07-20 18:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0002_denuncia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
